apiVersion: v1
kind: Service
metadata:
  labels:
    app: fake-datasource 
  name: fake-datasource
spec:
  ports:
  - name: http
    port: 3333
    protocol: TCP
    targetPort: 3333
  selector:
    app: fake-datasource 
  type: ClusterIP

